"""changed left to remaining

Revision ID: 27de3e75f0cc
Revises: 9d5e546f9ecb
Create Date: 2025-02-21 15:17:29.567408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27de3e75f0cc'
down_revision = '9d5e546f9ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloriesRemaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('proteinRemaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fatRemaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbRemaining', sa.Float(), nullable=True))
        batch_op.drop_column('fatLeft')
        batch_op.drop_column('proteinLeft')
        batch_op.drop_column('carbLeft')
        batch_op.drop_column('caloriesLeft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloriesLeft', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('carbLeft', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('proteinLeft', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fatLeft', sa.FLOAT(), nullable=True))
        batch_op.drop_column('carbRemaining')
        batch_op.drop_column('fatRemaining')
        batch_op.drop_column('proteinRemaining')
        batch_op.drop_column('caloriesRemaining')

    # ### end Alembic commands ###
