"""Updated UserMeals schema

Revision ID: 5e522d7f58fa
Revises: 
Create Date: 2025-02-20 13:15:35.557685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e522d7f58fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('fat')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
