"""Fixed column name typo

Revision ID: 8bd8ed25c46c
Revises: b5e7316c649b
Create Date: 2025-02-21 13:30:24.300452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd8ed25c46c'
down_revision = 'b5e7316c649b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proteinRatio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fatRatio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbRatio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('carbRatio')
        batch_op.drop_column('fatRatio')
        batch_op.drop_column('proteinRatio')

    # ### end Alembic commands ###
