"""Added macronutrient fields to User model

Revision ID: 9c5e5065c962
Revises: 5e522d7f58fa
Create Date: 2025-02-20 22:31:59.677220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5e5065c962'
down_revision = '5e522d7f58fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protienRequired', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fatRequired', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbRequired', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('carbRequired')
        batch_op.drop_column('fatRequired')
        batch_op.drop_column('protienRequired')

    # ### end Alembic commands ###
