"""Added daily macro tracking

Revision ID: 9d5e546f9ecb
Revises: 8bd8ed25c46c
Create Date: 2025-02-21 15:05:04.321884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5e546f9ecb'
down_revision = '8bd8ed25c46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloriesLeft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('proteinLeft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fatLeft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbLeft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_reset')
        batch_op.drop_column('carbLeft')
        batch_op.drop_column('fatLeft')
        batch_op.drop_column('proteinLeft')
        batch_op.drop_column('caloriesLeft')

    # ### end Alembic commands ###
