"""Added proteinRequired to User table

Revision ID: af7dab50bccd
Revises: 9c5e5065c962
Create Date: 2025-02-20 22:53:45.843974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7dab50bccd'
down_revision = '9c5e5065c962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protien', sa.Float(), nullable=False))
        batch_op.drop_column('protein')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.FLOAT(), nullable=False))
        batch_op.drop_column('protien')

    # ### end Alembic commands ###
