"""Force reapply macronutrient columns

Revision ID: b5e7316c649b
Revises: af7dab50bccd
Create Date: 2025-02-20 23:10:23.364634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e7316c649b'
down_revision = 'af7dab50bccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_meals')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proteinRequired', sa.Float(), nullable=True))
        batch_op.drop_column('protienRequired')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protienRequired', sa.FLOAT(), nullable=True))
        batch_op.drop_column('proteinRequired')

    op.create_table('_alembic_tmp_user_meals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), server_default=sa.text('1'), nullable=True),
    sa.Column('date_added', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('calories', sa.FLOAT(), nullable=False),
    sa.Column('carbs', sa.FLOAT(), nullable=False),
    sa.Column('fat', sa.FLOAT(), nullable=False),
    sa.Column('protien', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
